version: "3"

networks:
  app:
    driver: bridge

volumes:
  db:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  wp:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  portainer:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/portainer

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp:/var/www
    networks: 
      - app
    restart: always
    stdin_open: true 
    tty: true
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    networks: 
      - app
    restart: always
    stdin_open: true 
    tty: true
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on: 
      - mariadb
    volumes:
      - wp:/var/www
    networks: 
      - app
    restart: always
    stdin_open: true 
    tty: true
  adminer:
    build: ./requirements/adminer
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "4242:4242"
    networks:
     - app
    restart: always
    stdin_open: true 
    tty: true
  web:
    build: ./requirements/web
    container_name: web
    ports:
      - "80:80"
    networks:
     - app
    restart: always
    stdin_open: true 
    tty: true
  sftp:
    build: ./requirements/sftp
    container_name: sftp
    env_file: .env
    ports:
      - "2121:22"
    networks:
     - app
    volumes:
      - wp:/wp-data/${DB_USER}/upload
    restart: always
    stdin_open: true 
    tty: true
  portainer:
    image: "portainer/portainer-ce:2.11.1"
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    networks:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    restart: always
